<a href="https://colab.research.google.com/github/hagaryuu/data-analysis-basic-kadai/blob/main/NumPy%E3%81%A7%E9%85%8D%E5%88%97%E3%81%AE%E6%93%8D%E4%BD%9C%E3%82%84%E6%BC%94%E7%AE%97%E3%82%92%E3%81%97%E3%82%88%E3%81%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([[0,1],[2,3],[4,5]])
b = np.array([[0,1,2,3],[4,5,6,7]])

c = np.dot(a,b)

print(c)

np.max(c)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


47